# Generated by Django 4.1.4 on 2022-12-22 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RigDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=400)),
                ('tuning', models.TextField(max_length=200)),
                ('artistRig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rig_detail', to='metal.artistrig')),
            ],
        ),
        migrations.DeleteModel(
            name='RigDetails',
        ),
    ]
