# Generated by Django 4.1.4 on 2022-12-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0002_rigdetail_delete_rigdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo_url',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='artistrig',
            name='amplifier',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='artistrig',
            name='guitar',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='artistrig',
            name='pedal1',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='artistrig',
            name='pedal2',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='artistrig',
            name='pedal3',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='artistrig',
            name='photo_url',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='rigdetail',
            name='description',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='rigdetail',
            name='tuning',
            field=models.TextField(max_length=300),
        ),
    ]
