# Generated by Django 4.1.4 on 2022-12-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0004_artistrig_name_rigdetail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rigdetail',
            name='name',
            field=models.TextField(default='name', max_length=200),
        ),
    ]
