# Generated by Django 4.1.4 on 2022-12-23 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0005_alter_rigdetail_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rigdetail',
            name='name',
        ),
    ]
