# Generated by Django 4.1.4 on 2022-12-23 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0006_remove_rigdetail_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rigdetail',
            name='artistRig',
        ),
        migrations.AddField(
            model_name='rigdetail',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rig_detail', to='metal.artist'),
        ),
        migrations.AddField(
            model_name='rigdetail',
            name='name',
            field=models.TextField(default='', max_length=200, null=True),
        ),
    ]
