# Generated by Django 4.1.4 on 2022-12-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0007_remove_rigdetail_artistrig_rigdetail_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rigdetail',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
