# Generated by Django 4.1.4 on 2022-12-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0008_alter_rigdetail_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistrig',
            name='name',
        ),
    ]
