# Generated by Django 4.1.4 on 2022-12-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0009_remove_artistrig_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rigdetail',
            name='photo_url',
            field=models.TextField(max_length=600, null=True),
        ),
    ]
