# Generated by Django 4.1.4 on 2022-12-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0010_rigdetail_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rigdetail',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
