# Generated by Django 4.1.4 on 2022-12-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0013_remove_artistrig_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistrig',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
