# Generated by Django 4.1.4 on 2022-12-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0015_alter_artistrig_amplifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=500, null=True)),
                ('photo_url', models.CharField(default='no photo', max_length=250, null=True)),
                ('type', models.TextField(max_length=200)),
                ('color', models.TextField(max_length=200)),
            ],
        ),
    ]
