# Generated by Django 4.1.4 on 2023-01-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0016_gear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='photo_url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
